-- DropForeignKey
ALTER TABLE "AdAccount" DROP CONSTRAINT "AdAccount_BMId_fkey";

-- AlterTable
ALTER TABLE "AdAccount" ALTER COLUMN "BMId" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "BM" ALTER COLUMN "BMId" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "AdAccount" ADD CONSTRAINT "AdAccount_BMId_fkey" FOREIGN KEY ("BMId") REFERENCES "BM"("BMId") ON DELETE SET NULL ON UPDATE CASCADE;
